- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    template: ''
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: dev-ops-cle
        template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
        parameters_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.parameters.json'
